version: "3"

services:
  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - network

  app:
    image: myimg
    container_name: node 
    ports:
      - "3000:3000"
    networks:
      - network
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - network
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - app

networks:
  network: 
